# Generated by Django 3.2.9 on 2022-06-04 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Some String', max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Some String', max_length=150, verbose_name='Название работы')),
                ('salary', models.TextField(verbose_name='Зарплата')),
                ('type_of_work', models.CharField(max_length=150, verbose_name='Тип работы')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Слаг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job', to='job.categoryjob')),
            ],
        ),
    ]
