# Generated by Django 3.2.9 on 2022-06-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='type_of_work',
        ),
        migrations.AddField(
            model_name='job',
            name='an_experience',
            field=models.TextField(default='-----', verbose_name='Опыт Работы'),
        ),
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.TextField(default='-----', verbose_name='Оброзование'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(default='-----', verbose_name='Требования'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(default='-----', verbose_name='Обязаности'),
        ),
        migrations.AddField(
            model_name='job',
            name='schedule',
            field=models.TextField(default='-----', verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='job',
            name='working_conditions',
            field=models.TextField(default='-----', verbose_name='Условия работы'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.TextField(default='-----', verbose_name='Зарплата'),
        ),
        migrations.DeleteModel(
            name='CategoryJob',
        ),
    ]
