# Generated by Django 3.2.9 on 2022-06-05 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_banerimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BanerImage',
        ),
    ]
