# Generated by Django 3.2.9 on 2022-06-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_delete_banerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Some String', max_length=150, verbose_name='Название работы')),
                ('salary', models.TextField(default='-----', verbose_name='Зарплата')),
                ('requirements', models.TextField(default='-----', verbose_name='Требования')),
                ('responsibilities', models.TextField(default='-----', verbose_name='Обязаности')),
                ('working_conditions', models.TextField(default='-----', verbose_name='Условия работы')),
                ('an_experience', models.TextField(default='-----', verbose_name='Опыт Работы')),
                ('schedule', models.TextField(default='-----', verbose_name='График работы')),
                ('education', models.TextField(default='-----', verbose_name='Оброзование')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Слаг')),
            ],
        ),
    ]
