# Generated by Django 3.2.9 on 2022-06-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='summary',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Резюме'),
        ),
    ]
